modLoader = "javafml"
loaderVersion = "[39,)"
license = "AGPL v3"
[[mods]]
modId = "prioritytarget"
version = "2.0.0"
displayName = "PriorityTarget"
credits = "Idea from the game World of Warships"
authors = "Tapio"
description = '''
'''