modLoader = "javafml"
loaderVersion = "[39,)"
license = "AGPL v3"
[[mods]]
modId = "prioritytarget"
version = "1.0.0"
displayName = "PriorityTarget"
credits = "Idea from the World of Warships game"
authors = "Tapio"
description = '''
'''